# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_mptt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treenode',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
