# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_mptt', '0002_auto_20180802_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='treenode',
            name='sort_order',
            field=models.FloatField(default=1, max_length=50),
        ),
    ]
