# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_mptt', '0003_treenode_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
