# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_mptt', '0004_auto_20180802_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treenode',
            name='sort_order',
        ),
    ]
